### ISSUE TITLE
"dependencies" generated value in package.json is not according to the tutorial

### ISSUE THREAD

**Issue by RubenStefanssen** [SAP-samples/btp-end-to-end-scenario-use-cases#28]
After running

`cds add hana --for production`

in terminal, the "dependencies" generated value in package.json is not according to the tutorial

`"@sap/cds-hana": "^x"`

but is 

`"@cap-js/hana": "^1"`

**Comment by navinkrishnan** [comment]
`@cap-js/hana` is the latest driver.
Our document were updated to reflect this change https://github.com/SAP-samples/btp-end-to-end-scenario-use-cases/blob/main/topic3/production.md

Where do you see `@sap/cds-hana` ?

**Comment by navinkrishnan** [comment]
Tutorials are in process of update as cds 8 is recently released. It will reflect these changes sooner. Thanks
