### ISSUE TITLE
Pre-configured data for SAP Build apps

### ISSUE THREAD

**Issue by alebice** [SAP-samples/btp-end-to-end-scenario-use-cases#6]
Hello,
since I cannot access the example in BTP anymore, can you give more information on the data integrations you use in the SAP Build app that were preconfigured for this example? 
These are: 
S4HC_BASIC_DEFECT
S4HC_BASIC_PCLFN
S4HC_BASIC_PO
Which communication scenarios were used in this case?
Thank you!

**Comment by ilyabelozerovsap** [comment]
Sorry for the late answer - we have recognized that nobody is assigned as default issues processor.

We used the APIs described in api.sap.com.
For defects: https://api.sap.com/api/DEFECT_0001/overview
For classification: https://api.sap.com/api/OP_API_CLFN_PRODUCT_SRV/overview
For purchase orders: https://api.sap.com/api/CE_PURCHASEORDER_0001/overview

The communication scenarios are specified there in the links.
